import 'package:flutter/material.dart';

// ---- identity / mock constants ----
const myId = 'B3XK-7QMD-2FTV-9SLN-4HRW-6JYC-8PZB-5NKQ';
const c1 = 'K7QP-2M9X-4TVB-8HRS-J3NC-5WDY-6ZFM-Q2LX';
const c2 = 'T4RB-9NKM-3JWD-7XLP-2QCV-8HFY-5ZTB-8VQD';
const c3 = 'Z9HC-4LPM-8XKV-2WRT-6NDB-3JQY-7FSZ-M4KP';

String shortId(String id) =>
    '${id.substring(0, 4)}…${id.substring(id.length - 4)}';

// ---- Nocturne palette ----
class Pal {
  final Color shell, bg, surf, surf2, navbg, ink, muted, dim, line, lineSoft,
      accent, accLight, wash, tint, tintLine, tintInk, scrim, onAcc, accHover;
  const Pal({
    required this.shell,
    required this.bg,
    required this.surf,
    required this.surf2,
    required this.navbg,
    required this.ink,
    required this.muted,
    required this.dim,
    required this.line,
    required this.lineSoft,
    required this.accent,
    required this.accLight,
    required this.wash,
    required this.tint,
    required this.tintLine,
    required this.tintInk,
    required this.scrim,
    required this.onAcc,
    required this.accHover,
  });
}

const palDark = Pal(
  shell: Color(0xFF0B0C12),
  bg: Color(0xFF161826),
  surf: Color(0xFF232532),
  surf2: Color(0xFF1C1E2C),
  navbg: Color(0xFF1B1D2B),
  ink: Color(0xFFE9E9ED),
  muted: Color(0xFF9397AB),
  dim: Color(0xFF75798C),
  line: Color(0xFF3F424D),
  lineSoft: Color(0x24E9E9ED),
  accent: Color(0xFF9184D9),
  accLight: Color(0xFFB5ABFC),
  wash: Color(0x249184D9),
  tint: Color(0xFF2B2741),
  tintLine: Color(0xFF423A6A),
  tintInk: Color(0xFFD2CEFD),
  scrim: Color(0xA80B0C12),
  onAcc: Color(0xFF161826),
  accHover: Color(0xFFB5ABFC),
);

const palLight = Pal(
  shell: Color(0xFFCFD3E5),
  bg: Color(0xFFF3F5FE),
  surf: Color(0xFFE4E7F5),
  surf2: Color(0xFFECEFFB),
  navbg: Color(0xFFE9ECF8),
  ink: Color(0xFF292B31),
  muted: Color(0xFF595D6C),
  dim: Color(0xFF75798C),
  line: Color(0xFFCFD3E5),
  lineSoft: Color(0x24292B31),
  accent: Color(0xFF5D5294),
  accLight: Color(0xFF423A6A),
  wash: Color(0x1F5D5294),
  tint: Color(0xFFE7E5FE),
  tintLine: Color(0xFFB5ABFC),
  tintInk: Color(0xFF423A6A),
  scrim: Color(0x66292B31),
  onAcc: Color(0xFFF3F5FE),
  accHover: Color(0xFF423A6A),
);

const avPalDark = [
  Color(0xFF9184D9), Color(0xFF5D5294), Color(0xFF3F424D),
  Color(0xFFB5ABFC), Color(0xFF292B31), Color(0xFF796CBF),
];
const avPalLight = [
  Color(0xFF5D5294), Color(0xFFB5ABFC), Color(0xFFCFD3E5),
  Color(0xFF9184D9), Color(0xFFE7E5FE), Color(0xFF796CBF),
];

// ---- i18n ----
const Map<String, List<String>> jumpLabels = {
  'en': ['Onboarding', 'Secure device', 'My ID', 'Add', 'Chat list', 'Chat', 'Settings'],
  'de': ['Onboarding', 'Gerät absichern', 'Meine ID', 'Adden', 'Chatliste', 'Chat', 'Einstellungen'],
};

const Map<String, Map<String, String>> strings = {
  'en': {
    'h1a': 'No name.', 'h1b': 'No number.',
    'intro': 'BitDM creates an identity on this device. You get one long ID — that is all anyone needs to add you.',
    'b1': 'No phone number, no email', 'b2': 'Keys never leave the device', 'b3': 'No account, no recovery',
    'create': 'Create identity', 'createNote': 'Takes under a second. Works offline.',
    'wiped': 'All data was deleted. The old identity cannot be recovered.',
    'creating': 'Creating identity',
    'phraseTitle': 'Your 12 words',
    'phraseSub': 'This is the only way back if this phone is lost, broken or wiped. There is no server that could restore it for you.',
    'phraseWarn': 'Write them down on paper, in this order. Anyone who has them IS you. Never photograph them, never type them into a website.',
    'phraseDone': 'I wrote them down',
    'noChats': 'No conversations yet. Share your ID so someone can add you.',
    'badAddress': 'That is not a valid BitDM ID. Check for typos — the ID carries a checksum.',
    'safetyNumber': 'Safety number',
    'verifyNoSession': 'Available once you have exchanged a message. The number is derived from both keys.',

    'scanHint': 'Point the camera at the QR code of the other person. Nothing is stored, nothing is sent - the picture is only read on this device.',
    'scanNoCamera': 'No camera available. Without camera access the code cannot be read - you can paste the address instead.',
    'waitingForAccept': 'Request sent — waiting for confirmation',
    'locked': 'Locked',
    'lockedSub': 'The identity on this phone is sealed. It opens only with a factor you set up — the key itself is nowhere on this device in readable form, not with root, not with the file in hand.',
    'unlock': 'Unlock',
    'unlockStick': 'Use security key',
    'lockedNoFactor': 'No usable factor found for this identity. The slot file may be damaged. Your 12 words still restore the identity on another device — the messages on this phone are lost.',
    'stickIntro': 'The key holds a secret that cannot be copied off it. Setting up needs TWO touches: one to create the credential, one to fetch the secret. That is not a glitch — there is no other way.',
    'stickUsb': 'Plug in',
    'stickNfc': 'Tap',
    'stickPinLabel': 'Key PIN',
    'stickPinHint': 'The PIN of the security key, not of this phone. It never leaves the phone in the clear. Leave empty if the key has none.',
    'stickWorking': 'Touch the key when it blinks — twice.',
    'stickPinWrong': 'Wrong PIN.',
    'stickPinWrongLeft': 'Wrong PIN. {n} attempts left before the key locks itself for good.',
    'stickPinNeeded': 'This key has a PIN. Enter it above.',
    'stickLostNote': 'If the key is lost, this slot cannot be opened. Keep a second factor. Your 12 words still restore the identity on another device.',
    'lockNoScreenLock': 'No screen lock set',
    'lockNoScreenLockBody': 'This phone has no lock screen, so there is nothing to bind the key to. Set up a fingerprint or a PIN in the Android settings first — a lock that anyone can open would not be one.',
    'notifOne': 'New message',
    'notifMany': '{n} new messages',
    'fidoProbe': 'Test security key',
    'fidoHold': 'Hold your security key against the back of the phone. Only one command is sent: a question about what the key can do. Nothing is created, nothing is changed, no PIN is asked for.',
    'fidoNoNfc': 'NFC is off or not available. Turn it on in the Android settings.',
    'myId': 'My ID', 'myIdSub': 'Share it so someone can add you.', 'share': 'Share', 'copy': 'Copy', 'copied': 'Copied',
    'idNote': 'The ID holds no private key. Details under Settings › Security.',
    'addTitle': 'Add contact', 'idLabel': 'BitDM ID', 'paste': 'Paste', 'scan': 'Scan QR', 'sendReq': 'Send request',
    'pending': 'Pending', 'reqSentNote': 'Request sent. The chat opens once the other side confirms.',

    'addFoot': 'No messages are transmitted before confirmation. A contact can be removed unilaterally at any time.',
    'chats': 'Chats', 'wantsChat': 'Wants to start an encrypted chat with you.', 'accept': 'Accept', 'decline': 'Decline',
    'noNames': 'Contacts appear as an ID and a pattern. There are no names — not even local ones.',
    'encDetails': 'Encrypted · Details', 'message': 'Message', 'send': 'Send',
    'encryption': 'Encryption', 'protocol': 'Protocol', 'sessionKey': 'Session key', 'selfDestruct': 'Self-destructing messages',
    'selfDestructSub': 'Optional, per device', 'readReceipts': 'Read receipts', 'readReceiptsSub': 'Default: off',
    'verifyNote': 'Compare the session key in person to verify the other side.', 'close': 'Close',
    'secureTitle': 'Secure this device', 'secureSub': 'Your identity exists only here. Add at least one way to prove it is you before the app unlocks.',
    'secureFoot': 'You can add or remove factors later under Settings › Access.', 'secureSkip': 'Skip for now', 'secureDone': 'Continue',
    'access': 'Access', 'on2': 'Active', 'offMethod': 'Not set up', 'add': 'Set up', 'remove': 'Remove',
    'bio': 'Biometrics', 'bioSub': 'Fingerprint or face unlock on this device',

    'devpin': 'Device lock', 'devpinSub': 'The PIN, pattern or password of this phone',
    'pw': 'App password', 'pwSub': 'A password only for BitDM — stays in your head',
    'enrollPw': 'Set an app password',
    'pwIntro': 'This slot hangs on NOTHING but the password. No secure area, no key. Anyone who copies the slot file can try on their own hardware for as long as they like — Argon2id makes every attempt expensive, but it cannot make a short password long.',
    'pwHint': 'Password',
    'pwAgain': 'Again',
    'pwMismatch': 'The two entries differ.',
    'pwWeak': 'Too short. That gives roughly {ist} bits, and at least {soll} are needed. Four or five random words are easier to remember than a short cryptic one — and far stronger.',
    'pwLostNote': 'Forgotten means gone. There is no reset. Your 12 words still restore the identity on another device.',
    'pwUnlockHint': 'Your BitDM app password. Not the phone PIN, not the security key PIN.',
    'unlockBio': 'Fingerprint',
    'unlockDevPin': 'Device lock',
    'unlockPw': 'App password',
    'unlockFailed': 'That did not open the slot.',
    'receiving': 'Receiving',
    'bgReceive': 'Receive in the background',
    'bgReceiveSub': 'Whether messages arrive while the app is closed',
    'bgOff': 'Off', 'bgLive': 'Live', 'bg15': '15 min', 'bg60': '1 h', 'bg240': '4 h',
    'bgOffNote': 'Messages arrive when you open the app. Nothing runs in the background, nothing costs battery, no permanent notification. Fine if you check BitDM anyway — nothing is lost, the relay holds messages for 14 days.',
    'bgLiveNote': 'Constantly connected — messages arrive the moment they are sent. Costs the most battery, but far less than it sounds: an idle connection is a few packets an hour. Pick this if BitDM is how people actually reach you.',
    'bg15Note': 'Connects briefly every 15 minutes. Feels almost live and uses noticeably less battery than a constant connection. The sensible middle, and what most people should pick.',
    'bg60Note': 'Once an hour. Enough if nobody is waiting for an instant reply. Barely measurable on the battery.',
    'bg240Note': 'Four times a day. For anyone who treats BitDM like a mailbox rather than a chat.',
    'bgConflict': 'This does not work right now: the relay only answers with a signature from your identity key, and that key sits behind the app lock. With "Lock again after: Instantly" the app has no key the moment you put it down. Set the lock delay to 5 minutes or Never — or accept that messages arrive when you open the app.',
    'bgNotifTitle': 'BitDM',
    'bgNotifText': 'Ready to receive',
    'lockDelay': 'Lock again after',
    'lockDelaySub': 'How long the app may stay open in the background',
    'delayNow': 'Instantly', 'delay1m': '1 min', 'delay5m': '5 min', 'delayNever': 'Never',
    'hw': 'Hardware security key', 'hwSub': 'FIDO2 key over USB-C or NFC',

    'enrollHw': 'Insert or tap your key',

 'waiting': 'Waiting for device',
    'minOne': 'At least one factor stays required.',
    'settings': 'Settings', 'general': 'General', 'security': 'Security', 'identity': 'Identity', 'emergency': 'Emergency',
    'language': 'Language', 'languageSub': 'App-wide', 'appearance': 'Appearance', 'appearanceSub': 'Dark by default',
    'screenshot': 'Screenshot protection', 'screenshotSub': 'Warning in chat, preview blocked',
    'myIdQr': 'My ID & QR', 'fingerprint': 'Key fingerprint',
    'panic': 'Panic mode', 'panicSub': 'Delete identity, contacts and messages instantly and irreversibly.',
    'panicTitle': 'Delete everything?', 'panicBody': 'This identity, all contacts and all messages will be removed from this device. There is no recovery.',
    'cancel': 'Cancel', 'delete': 'Delete',
    'dark': 'Dark', 'light': 'Light', 'off': 'Off', 'h1': '1 hour', 'h24': '24 hours', 'd7': '7 days', 'on': 'On',
    'navChats': 'Chats', 'navId': 'My ID', 'navSet': 'Settings',
    'voice': 'Voice message', 'newContact': 'New contact',

    'hintShot': 'Screenshot protection on', 'hintEnc': 'End-to-end encrypted', 'hintEph': 'Messages delete after ',
  },
  'de': {
    'h1a': 'Kein Name.', 'h1b': 'Keine Nummer.',
    'intro': 'BitDM erzeugt eine Identität auf diesem Gerät. Du erhältst eine lange ID — sie ist alles, was andere brauchen, um dich hinzuzufügen.',
    'b1': 'Keine Telefonnummer, keine E-Mail', 'b2': 'Schlüssel verlassen das Gerät nicht', 'b3': 'Kein Konto, keine Wiederherstellung',
    'create': 'Identität erstellen', 'createNote': 'Dauert unter einer Sekunde. Offline möglich.',
    'wiped': 'Alle Daten wurden gelöscht. Die alte Identität ist nicht wiederherstellbar.',
    'creating': 'Identitaet wird angelegt',
    'phraseTitle': 'Deine 12 Woerter',
    'phraseSub': 'Das ist der einzige Weg zurueck, wenn dieses Telefon verloren, kaputt oder geloescht ist. Es gibt keinen Server, der sie wiederherstellen koennte.',
    'phraseWarn': 'Schreib sie auf Papier, in dieser Reihenfolge. Wer sie hat, IST du. Niemals abfotografieren, niemals auf einer Webseite eingeben.',
    'phraseDone': 'Habe ich notiert',
    'noChats': 'Noch keine Unterhaltungen. Teile deine ID, damit dich jemand hinzufuegen kann.',
    'badAddress': 'Das ist keine gueltige BitDM-ID. Pruefe auf Tippfehler — die ID traegt eine Pruefsumme.',
    'safetyNumber': 'Pruefnummer',
    'verifyNoSession': 'Verfuegbar, sobald ihr eine Nachricht ausgetauscht habt. Die Nummer entsteht aus beiden Schluesseln.',

    'scanHint': 'Halte die Kamera auf den QR-Code des anderen. Es wird nichts gespeichert und nichts gesendet - das Bild wird nur auf diesem Geraet gelesen.',
    'scanNoCamera': 'Keine Kamera verfuegbar. Ohne Kamerazugriff laesst sich der Code nicht lesen - du kannst die Adresse stattdessen einfuegen.',
    'waitingForAccept': 'Anfrage gesendet — wartet auf Bestaetigung',
    'locked': 'Gesperrt',
    'lockedSub': 'Die Identität auf diesem Telefon ist verschlossen. Sie geht nur mit einem eingerichteten Faktor auf — der Schlüssel selbst liegt nirgends lesbar auf diesem Gerät, auch nicht mit Root, auch nicht mit der Datei in der Hand.',
    'unlock': 'Entsperren',
    'unlockStick': 'Mit Sicherheitsschlüssel',
    'lockedNoFactor': 'Zu dieser Identität ist kein brauchbarer Faktor eingerichtet. Vermutlich ist die Fachdatei beschädigt. Deine 12 Wörter holen die Identität auf einem anderen Gerät zurück — die Nachrichten auf diesem Telefon sind verloren.',
    'stickIntro': 'Der Schlüssel trägt ein Geheimnis, das sich nicht von ihm herunterkopieren lässt. Das Einrichten braucht ZWEI Berührungen: eine, um den Zugang anzulegen, eine, um das Geheimnis zu holen. Das ist kein Fehler — anders geht es nicht.',
    'stickUsb': 'Einstecken',
    'stickNfc': 'Auflegen',
    'stickPinLabel': 'PIN des Schlüssels',
    'stickPinHint': 'Die PIN des Sicherheitsschlüssels, nicht die dieses Telefons. Sie verlässt das Telefon nie im Klartext. Leer lassen, wenn der Schlüssel keine hat.',
    'stickWorking': 'Berühre den Schlüssel, wenn er blinkt — zweimal.',
    'stickPinWrong': 'PIN falsch.',
    'stickPinWrongLeft': 'PIN falsch. Noch {n} Versuche, dann sperrt sich der Schlüssel endgültig.',
    'stickPinNeeded': 'Dieser Schlüssel hat eine PIN. Gib sie oben ein.',
    'stickLostNote': 'Geht der Schlüssel verloren, lässt sich dieses Fach nicht mehr öffnen. Richte einen zweiten Faktor ein. Deine 12 Wörter holen die Identität auf einem anderen Gerät zurück.',
    'lockNoScreenLock': 'Keine Bildschirmsperre eingerichtet',
    'lockNoScreenLockBody': 'Dieses Telefon hat keine Bildschirmsperre, also gibt es nichts, woran sich der Schluessel binden liesse. Richte in den Android-Einstellungen zuerst einen Fingerabdruck oder eine PIN ein — eine Sperre, die jeder oeffnet, waere keine.',
    'notifOne': 'Neue Nachricht',
    'notifMany': '{n} neue Nachrichten',
    'fidoProbe': 'Sicherheitsschluessel pruefen',
    'fidoHold': 'Halte deinen Sicherheitsschluessel an die Rueckseite des Telefons. Es geht genau ein Befehl raus: die Frage, was der Stick kann. Es wird nichts angelegt, nichts geaendert und keine PIN verlangt.',
    'fidoNoNfc': 'NFC ist aus oder nicht verfuegbar. In den Android-Einstellungen einschalten.',
    'myId': 'Meine ID', 'myIdSub': 'Teile sie, damit dich jemand hinzufügen kann.', 'share': 'Teilen', 'copy': 'Kopieren', 'copied': 'Kopiert',
    'idNote': 'Die ID enthält keinen privaten Schlüssel. Details unter Einstellungen › Sicherheit.',
    'addTitle': 'Kontakt hinzufügen', 'idLabel': 'BitDM-ID', 'paste': 'Einfügen', 'scan': 'QR scannen', 'sendReq': 'Anfrage senden',
    'pending': 'Ausstehend', 'reqSentNote': 'Anfrage gesendet. Der Chat öffnet sich, sobald die Gegenseite bestätigt.',

    'addFoot': 'Vor der Bestätigung werden keine Nachrichten übertragen. Ein Kontakt kann jederzeit einseitig entfernt werden.',
    'chats': 'Chats', 'wantsChat': 'Möchte einen verschlüsselten Chat mit dir beginnen.', 'accept': 'Annehmen', 'decline': 'Ablehnen',
    'noNames': 'Kontakte erscheinen als ID und Muster. Namen gibt es nicht — auch nicht lokal.',
    'encDetails': 'Verschlüsselt · Details', 'message': 'Nachricht', 'send': 'Senden',
    'encryption': 'Verschlüsselung', 'protocol': 'Protokoll', 'sessionKey': 'Sitzungsschlüssel', 'selfDestruct': 'Selbstlöschende Nachrichten',
    'selfDestructSub': 'Optional, pro Gerät', 'readReceipts': 'Lesebestätigungen', 'readReceiptsSub': 'Standard: aus',
    'verifyNote': 'Vergleiche den Sitzungsschlüssel persönlich, um die Gegenseite zu verifizieren.', 'close': 'Schließen',
    'secureTitle': 'Gerät absichern', 'secureSub': 'Deine Identität liegt nur hier. Richte mindestens einen Nachweis ein, bevor die App entsperrt.',
    'secureFoot': 'Faktoren lassen sich später unter Einstellungen › Zugriff ergänzen oder entfernen.', 'secureSkip': 'Später', 'secureDone': 'Weiter',
    'access': 'Zugriff', 'on2': 'Aktiv', 'offMethod': 'Nicht eingerichtet', 'add': 'Einrichten', 'remove': 'Entfernen',
    'bio': 'Biometrie', 'bioSub': 'Fingerabdruck oder Gesichtsentsperrung dieses Geräts',

    'devpin': 'Gerätesperre', 'devpinSub': 'Die PIN, das Muster oder das Passwort dieses Telefons',
    'pw': 'App-Passwort', 'pwSub': 'Ein Passwort nur für BitDM — bleibt in deinem Kopf',
    'enrollPw': 'App-Passwort festlegen',
    'pwIntro': 'Dieses Fach hängt an NICHTS außer dem Passwort. Kein gesicherter Bereich, kein Schlüssel. Wer die Fachdatei kopiert, kann auf eigener Hardware probieren, so lange er will — Argon2id verteuert jeden Versuch, aber aus einem kurzen Passwort macht es kein langes.',
    'pwHint': 'Passwort',
    'pwAgain': 'Wiederholen',
    'pwMismatch': 'Die beiden Eingaben sind verschieden.',
    'pwWeak': 'Zu kurz. Das gibt rund {ist} Bit her, nötig sind mindestens {soll}. Vier oder fünf zufällige Wörter merkt man sich leichter als ein kurzes kryptisches — und sie sind erheblich stärker.',
    'pwLostNote': 'Vergessen heißt weg. Es gibt kein Zurücksetzen. Deine 12 Wörter holen die Identität auf einem anderen Gerät zurück.',
    'pwUnlockHint': 'Dein BitDM-Passwort. Nicht die Telefon-PIN und nicht die PIN des Sicherheitsschlüssels.',
    'unlockBio': 'Fingerabdruck',
    'unlockDevPin': 'Gerätesperre',
    'unlockPw': 'App-Passwort',
    'unlockFailed': 'Damit ging das Fach nicht auf.',
    'receiving': 'Empfang',
    'bgReceive': 'Im Hintergrund empfangen',
    'bgReceiveSub': 'Ob Nachrichten ankommen, während die App zu ist',
    'bgOff': 'Aus', 'bgLive': 'Ständig', 'bg15': '15 Min.', 'bg60': '1 Std.', 'bg240': '4 Std.',
    'bgOffNote': 'Nachrichten kommen an, wenn du die App öffnest. Nichts läuft im Hintergrund, nichts kostet Akku, keine dauerhafte Benachrichtigung. Reicht, wenn du ohnehin regelmäßig reinschaust — verloren geht nichts, der Relay hält Nachrichten 14 Tage.',
    'bgLiveNote': 'Ständig verbunden — Nachrichten kommen in dem Moment an, in dem sie gesendet werden. Kostet am meisten Akku, aber deutlich weniger, als es klingt: eine ruhende Verbindung sind ein paar Pakete pro Stunde. Nimm das, wenn dich Leute wirklich über BitDM erreichen.',
    'bg15Note': 'Verbindet sich alle 15 Minuten kurz. Fühlt sich fast wie ständig an und braucht spürbar weniger Akku. Der sinnvolle Mittelweg — und das, was für die meisten richtig ist.',
    'bg60Note': 'Einmal pro Stunde. Reicht, wenn niemand auf eine sofortige Antwort wartet. Am Akku kaum messbar.',
    'bg240Note': 'Viermal am Tag. Für alle, die BitDM eher wie ein Postfach behandeln als wie einen Chat.',
    'bgConflict': 'Das geht gerade nicht: der Relay antwortet nur auf eine Unterschrift mit deinem Identitätsschlüssel, und der liegt hinter der App-Sperre. Bei „Wieder sperren nach: Sofort" hat die App keinen Schlüssel, sobald du sie weglegst. Stell die Sperrfrist auf 5 Minuten oder Nie — oder nimm hin, dass Nachrichten beim Öffnen ankommen.',
    'bgNotifTitle': 'BitDM',
    'bgNotifText': 'Empfangsbereit',
    'lockDelay': 'Wieder sperren nach',
    'lockDelaySub': 'Wie lange die App im Hintergrund offen bleiben darf',
    'delayNow': 'Sofort', 'delay1m': '1 Min.', 'delay5m': '5 Min.', 'delayNever': 'Nie',
    'hw': 'Hardware-Sicherheitsschlüssel', 'hwSub': 'FIDO2-Schlüssel über USB-C oder NFC',

    'enrollHw': 'Schlüssel einstecken oder auflegen',

 'waiting': 'Warte auf Gerät',
    'minOne': 'Mindestens ein Faktor bleibt erforderlich.',
    'settings': 'Einstellungen', 'general': 'Allgemein', 'security': 'Sicherheit', 'identity': 'Identität', 'emergency': 'Notfall',
    'language': 'Sprache', 'languageSub': 'Gilt für die ganze App', 'appearance': 'Erscheinungsbild', 'appearanceSub': 'Standard: dunkel',
    'screenshot': 'Screenshot-Schutz', 'screenshotSub': 'Warnhinweis im Chat, Vorschau geblockt',
    'myIdQr': 'Meine ID & QR', 'fingerprint': 'Schlüssel-Fingerprint',
    'panic': 'Panik-Modus', 'panicSub': 'Identität, Kontakte und Nachrichten sofort und unwiderruflich löschen.',
    'panicTitle': 'Alles löschen?', 'panicBody': 'Diese Identität, alle Kontakte und alle Nachrichten werden von diesem Gerät entfernt. Es gibt keine Wiederherstellung.',
    'cancel': 'Abbrechen', 'delete': 'Löschen',
    'dark': 'Dunkel', 'light': 'Hell', 'off': 'Aus', 'h1': '1 Std.', 'h24': '24 Std.', 'd7': '7 Tage', 'on': 'An',
    'navChats': 'Chats', 'navId': 'Meine ID', 'navSet': 'Einstellungen',
    'voice': 'Sprachnachricht', 'newContact': 'Neuer Kontakt',

    'hintShot': 'Screenshot-Schutz aktiv', 'hintEnc': 'Ende-zu-Ende verschlüsselt', 'hintEph': 'Nachrichten löschen sich nach ',
  },
};
